### ISSUE TITLE
a error when train with TSN3D

### ISSUE THREAD

**Issue by Tylerjoe** [decisionforce/TPN#11]
Thanks for your great work!
when i follow the following command to train the TSN2D, it's ok:
`python tools/train_recognizer.py config_files/sthv2/tsm_tpn.py`

but after i chang the configure file to 3d network, as following:
`python tools/train_recognizer.py config_files/kinetics400/tpn/r101f32s2.py`

I got the error as following:
> Traceback (most recent call last):
>   File "tools/train_recognizer.py", line 92, in <module>
>     main()
>   File "tools/train_recognizer.py", line 88, in main
>     logger=logger)
>   File "/data/download/projects/clover_tpn_train/mmaction/apis/train.py", line 59, in train_network
>     _non_dist_train(model, dataset, cfg, validate=validate)
>   File "/data/download/projects/clover_tpn_train/mmaction/apis/train.py", line 191, in _non_dist_train
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
>   File "/root/anaconda3/envs/pytorch1.4/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/root/anaconda3/envs/pytorch1.4/lib/python3.6/site-packages/mmcv/runner/runner.py", line 264, in train
>     self.model, data_batch, train_mode=True, **kwargs)
>   File "/data/download/projects/clover_tpn_train/mmaction/apis/train.py", line 36, in batch_processor
>     losses = model(**data)
>   File "/root/anaconda3/envs/pytorch1.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/root/anaconda3/envs/pytorch1.4/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/root/anaconda3/envs/pytorch1.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/download/projects/clover_tpn_train/mmaction/models/recognizers/base.py", line 39, in forward
>     return self.forward_train(num_modalities, img_meta, **kwargs)
>   File "/data/download/projects/clover_tpn_train/mmaction/models/recognizers/TSN3D.py", line 100, in forward_train
>     x, aux_losses = self.necks(x, gt_label.squeeze())
>   File "/root/anaconda3/envs/pytorch1.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/download/projects/clover_tpn_train/mmaction/models/tenons/necks/tpn.py", line 324, in forward
>     topdownouts = self.level_fusion_op2(outs)
>   File "/root/anaconda3/envs/pytorch1.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/download/projects/clover_tpn_train/mmaction/models/tenons/necks/tpn.py", line 170, in forward
>     out = torch.cat(out, 1)
> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 7 and 4 in dimension 3 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71

**Comment by limbo0000** [comment]
Hi @Tylerjoe 
Could you successfully run with config_files/kinetics400/tpn/r50f8s8.py?

**Comment by Tylerjoe** [comment]
> Hi @Tylerjoe
> Could you successfully run with config_files/kinetics400/tpn/r50f8s8.py?

Thanks for your quick reply, I have run with config_files/kinetics400/tpn/r50f8s8.py successfully.
is there any difference between r50f8s8.py and r101f32s2.py except backbone？

**Comment by limbo0000** [comment]
Hi @Tylerjoe ,
Thanks to your issue helping figure out the errors in config files of r101-tpn. Yeah, there exists a difference between the [r50](https://github.com/decisionforce/TPN/blob/182dae01a2a6faa422c7195ea6348f88c6b781e2/config_files/kinetics400/tpn/r50f32s2.py#L30)  and [r101](https://github.com/decisionforce/TPN/blob/182dae01a2a6faa422c7195ea6348f88c6b781e2/config_files/kinetics400/tpn/r101f32s2.py#L30) . The scale of temporal downsample is slightly different, which leads to the shape inconsistency of various features. The performance is almost the same if r101 also takes the same scale for temporal downsample. In order to match the released models, we have to maintain the original one. 

I updated the lastest configs for r101. You can try it again. Please let me know if you have any other question, and thank you again!

**Comment by limbo0000** [comment]
I would close this issue, you can reopen it if there remains any question.

**Comment by Tylerjoe** [comment]
Thanks for dealing with the problem so quickly!

after update the configure file, it can run successfully
