### ISSUE TITLE
--validate not working for non-distributed mode

### ISSUE THREAD

**Issue by nirat1606** [decisionforce/TPN#13]
I'm trying to train a model, and want to use validate mode, but in non-distributed mode, validate doesn't work since in /mmaction/apis/train.py there is no use of validate in the method  _non_dist_train(model, dataset, cfg, validate=validate). Could you update the code for running validate in non-distributed mode?

Also, I could not run the code in distributed mode (with --launcher=pytorch, 2GPUs). Can you explain what is the difference in different modes and how to use those for running train in distributed mode?

Thanks,

**Comment by justimyhxu** [comment]
--validate only works for distributed mode.
