### ISSUE TITLE
Error when running test on demo video with kinetic models

### ISSUE THREAD

**Issue by SUYEgit** [decisionforce/TPN#15]
I was trying to run model "kinetics400_tpn_r101f16s4.pth" on demo video by running the "test_video.py" scripts and I met following error, could you please help me? Is that because demo/category.txt is categories of dataset "something something"? 
`python test_video.py config_files/kinetics400/tpn/r101f16s4.py ckpt/ft_local/kinetics400_tpn_r101f16s4.pth`
![image](https://user-images.githubusercontent.com/35247113/88369910-9fb55780-cdc3-11ea-9dfb-a6023bd6b978.png)

**Comment by limbo0000** [comment]
@SUYEgit  Yes, currently, our 'test_video.py' only supports the categories on Something-Something dataset.

**Comment by SUYEgit** [comment]
Thanks for you reply. Then how do I test your models trained on Kinetics?
