### ISSUE TITLE
How long have the models been trained?

### ISSUE THREAD

**Issue by limingcv** [decisionforce/TPN#22]
Thanks for your contribution, as a freshman, I have no idea how long should it take to train a model? I have read this paper, but I still don’t know how long the training time of the model is.

Thanks again!

**Comment by limbo0000** [comment]
Hi @limingcv,
The training time also depends on the dataset you choose and the GPU server. It seems to take 5 days to train a R50 (Kinetics-400) on 8GPUs server.

**Comment by limingcv** [comment]
Thanks a lot

Ceyuan Yang <notifications@github.com> 于2020年9月24日周四 下午5:19写道：
