### ISSUE TITLE
Could you explain some parameters in code?

### ISSUE THREAD

**Issue by limingcv** [decisionforce/TPN#23]
Thanks for your contribution! I have read code but there are still some questions I can't understand.

The main question is the parameters to sample frames in `mmaction/datasets/rawframes_datasets.py`, from row 65 to row 72

```python
# parameters for frame fetching
# number of segments
self.num_segments = num_segments
# number of consecutive frames
self.old_length = new_length * new_step
self.new_length = new_length
# number of steps (sparse sampling for efficiency of io)
self.new_step = new_step
```

Could I understand it as following descriptions?

* The chosen video is divided into `num_segments` clips, each clip has `record.num_frames // num_segments` frames
* Sample `new_length` frame(s) in a clip, totally sampling `new_length * num_segments` frames for a video
* In a clip, sampling `new_length` frames with interval `new_step`

As a freshman, this really bother me a lot, I'm really appreciate it if you can help me!

Thanks again for your contribution!

**Comment by limbo0000** [comment]
Hi @limingcv,
Yes. Your understand is correct. It involves two different sampling strategies: sparse and dense sampling. For sparse sampling which is usually adopted in TSN-like models, the whole video is divided into N segments and then we only choose one frame per segment.  Such that, we could obtain N x 1 frames. For dense sampling (\eg I3D), we always care about the number of frames and their interval (\ie new_length and new_step).

**Comment by limingcv** [comment]
Thanks a lot!
