### ISSUE TITLE
Use RWF-2000 to train TPN

### ISSUE THREAD

**Issue by bujianyiwang** [decisionforce/TPN#26]
How can I deal with RWF-2000 when following the instruction of Data Preparation? My dataset is RWF-2000 which contatins train and val folder,label is only Fight and NonFight.

**Comment by limbo0000** [comment]
Hi @bujianyiwang , I am not familiar to RWF-2000. Maybe this problem could be regarded as the binary classification. If so, label 0 and 1 denote fight and nonfight respectively.
