### ISSUE TITLE
I want to know how to down checkpoint

### ISSUE THREAD

**Issue by pokameng** [decisionforce/TPN#27]
I want to know how to down checkpoint

**Comment by limbo0000** [comment]
Hi @pokameng , you can click the link of each model in MODEL_ZOO. They are the shared link for google drive.

**Comment by pokameng** [comment]
Thank you very much,but I want to&nbsp;
know&nbsp; how to solve this probles?
在执行这个的时候
python&nbsp;./tools/test_recognizer.py&nbsp;config_files/kinetics400/tpn/r50f8s8.py&nbsp;ckpt/kinetics400_tpn_r50f8s8&nbsp;--gpus&nbsp;&nbsp;1&nbsp;&nbsp;--out&nbsp;ckpt/kinetics400_tpn_r50f8s8.pkl&nbsp;--fcn_testing&nbsp;--ignore_cache

Traceback (most recent call last):   File "./tools/test_recognizer.py", line 9, in <module&gt;     from mmcv.runner import load_checkpoint, parallel_test, obj_from_dict, get_dist_info ImportError: cannot import name 'parallel_test'
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "decisionforce/TPN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月28日(星期六) 晚上10:20
收件人:&nbsp;"decisionforce/TPN"<TPN@noreply.github.com&gt;;
抄送:&nbsp;"繁华落尽"<1169138654@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [decisionforce/TPN] I want to know how to down checkpoint (#27)





 
Hi @pokameng , you can click the link of each model in MODEL_ZOO. They are the shared link for google drive.
