### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'img_meta'

### ISSUE THREAD

**Issue by DAVEISHAN** [decisionforce/TPN#6]
Hi,
First of all, thank you for sharing the code! I am excited to try it on my dataset. 

Just to make sure my code works, I am trying to pass the random input to the TPN model and getting this error 'TypeError: forward() missing 1 required positional argument: 'img_meta'.  (link to the code shared below)

I am using the config file from this file: TPN/config_files/kinetics400/tpn/r101f16s4.py

pl find my code at: 
https://knightsucfedu39751-my.sharepoint.com/:u:/g/personal/ishandave_knights_ucf_edu/EdLeO1o7QFlLizGP7KBg0WwBgIOOICwL8PEjy4yYZjLyxg?e=M9IdyZ

output of the code: 
https://knightsucfedu39751-my.sharepoint.com/:t:/g/personal/ishandave_knights_ucf_edu/EVtXye2qsFxCvcBqkddxiwABbN2EXjYoGLBUEcSTcoJVHA?e=VwiypD

Hope to hear from you soon.

-Ishan

**Comment by limbo0000** [comment]
Hi @DAVEISHAN,
Please refer to the forward of [TSN3D](https://github.com/decisionforce/TPN/blob/1b3568ecc0509e9210ca8f33dad98f73c8a8a80c/mmaction/models/recognizers/TSN3D.py#L85) and [BaseRecognizer](https://github.com/decisionforce/TPN/blob/1b3568ecc0509e9210ca8f33dad98f73c8a8a80c/mmaction/models/recognizers/base.py#L36) and be careful about the type and parameters of input.
Perhaps you could call model.forward_test explicitly and generate a dictionary to contain your input data whose keys are declared in [dataloader](https://github.com/decisionforce/TPN/blob/1b3568ecc0509e9210ca8f33dad98f73c8a8a80c/mmaction/datasets/rawframes_dataset.py#L313).

**Comment by Note-Liu** [comment]
I also meet this bug,how did you solve it?
