### ISSUE TITLE
Use my own dataset to train the model

### ISSUE THREAD

**Issue by zhulishun** [decisionforce/TPN#7]
If I want to use my dataset to train a model, what parts need to be modified？

**Comment by limbo0000** [comment]
Hi @zhulishun, 
Please follow the [instruction](https://github.com/decisionforce/TPN/blob/master/data/README.md) of Data Preparation, including the txt file to generate and parameters to modify for config files.

**Comment by zhulishun** [comment]
thanks

**Comment by limbo0000** [comment]
I would close this issue. You could reopen it if there remain some problems.

**Comment by bujianyiwang** [comment]
@zhulishun How do you deal with your own dataset when following the instruction of Data Preparation? My dataset is RWF-2000 which contatins train and val folder,label is only Fight and NonFight.
